# Run docker in travis

sudo: required

# don't need to install R
language: generic

services:
  - docker

before_install:
    # create & run container, i.e. compile pkg and render Rmd to Word doc
  - docker build -t benmarwick/researchcompendium .

# always!
# warnings_are_errors: false


# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# language: R
# sudo: false
# cache:
#   directories: $TRAVIS_BUILD_DIR/packrat/
#   packages: true
#
# install:
#   - R -e "0" --args --bootstrap-packrat
#
# warnings_are_errors: false
#
# after_success:
#   - bash <(curl -s https://codecov.io/bash) -t 9698fc31-0018-4b43-896b-60503df4d0e0
#
